CREATE TABLE Towns(
	Id INT IDENTITY(1, 1) PRIMARY KEY,
	Name VARCHAR(50) NOT NULL
);

CREATE TABLE Addresses(
	Id INT IDENTITY(1, 1) PRIMARY KEY,
	AddressText VARCHAR(250) NOT NULL,
	TownId INT FOREIGN KEY REFERENCES Towns(Id)
);

CREATE TABLE Departments(
	Id INT IDENTITY(1, 1) PRIMARY KEY,
	Name VARCHAR(50) NOT NULL
);

CREATE TABLE Employees(
	Id INT IDENTITY(1, 1) PRIMARY KEY,
	FirstName VARCHAR(50) NOT NULL,
	MiddleName VARCHAR(50) NOT NULL,
	LastName VARCHAR(50) NOT NULL,
	JobTitle VARCHAR(50) NOT NULL,
	DepartmentId INT FOREIGN KEY REFERENCES Departments(Id),
	HireDate DATETIME2,
	Salary MONEY,
	AddressId INT FOREIGN KEY REFERENCES Addresses(Id),
	

);